# Generated by Django 2.1.7 on 2019-05-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_post_mainphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='mainphoto',
            new_name='photo',
        ),
    ]
